import productSlugRedirects from "./shared/config/product-slug-redirects.json" with { type: "json" };

/** @type {import('next').NextConfig} */
const nextConfig = {
  /**
   * 301s from the old `{brand}-{counter}` product URLs to the keyword slugs.
   * The file is generated by shop-backend/scripts/seo/apply.mjs and is an empty array until
   * that runs, so this is a no-op before the rename.
   */
  async redirects() {
    // `permanent: true` would emit 308. Google treats 308 as equivalent to 301, but 301 is what
    // every crawler and analytics tool understands, so the status is pinned explicitly.
    return productSlugRedirects.map((entry) => ({ ...entry, statusCode: 301 }));
  },
  // standalone output for a lightweight Docker image (self-contained server.js, reads PORT/HOSTNAME)
  output: "standalone",
  // Allow dev-server access from the network/WSL IP (fixes the cross-origin warning)
  allowedDevOrigins: ["localhost"],
  experimental: {
    viewTransition: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
